### PR TITLE
supply a default highlight color for createDiff. fixes #27

### LINKED ISSUE #27: highlightColor undefined issue
Basically `highlightColor` being undefined is causing this error and it wasn't obvious that it was `highlightColor` to blame:

```sh
TypeError: Cannot read property '0' of undefined
    at parseColorString (/Users/niftylettuce/Public/project/node_modules/looks-same/index.js:170:22)
    at readPair (/Users/niftylettuce/Public/project/node_modules/looks-same/index.js:218:29)
    at readFunc (/Users/niftylettuce/Public/project/node_modules/looks-same/index.js:40:17)
    at png.parse (/Users/niftylettuce/Public/project/node_modules/looks-same/lib/png.js:120:15)
    at exports.PNG.<anonymous> (/Users/niftylettuce/Public/project/node_modules/pngjs/lib/png.js:75:7)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at exports.PNG.emit (events.js:210:7)
    at exports.PNG.<anonymous> (/Users/niftylettuce/Public/project/node_modules/pngjs/lib/png.js:37:10)
    at emitOne (events.js:115:13)
    at module.exports.emit (events.js:210:7)
    at module.exports.ParserAsync._complete (/Users/niftylettuce/Public/project/node_modules/pngjs/lib/parser-async.js:145:8)
    at emitOne (events.js:115:13)
    at module.exports.emit (events.js:210:7)
    at module.exports.complete (/Users/niftylettuce/Public/project/node_modules/pngjs/lib/filter-parse-async.js:19:12)
    at module.exports.Filter._reverseFilterLine (/Users/niftylettuce/Public/project/node_modules/pngjs/lib/filter-parse.js:169:10)
    at module.exports.ChunkStream._processRead (/Users/niftylettuce/Public/project/node_modules/pngjs/lib/chunkstream.js:174:13)
    at module.exports.ChunkStream._process (/Users/niftylettuce/Public/project/node_modules/pngjs/lib/chunkstream.js:193:14)
    at module.exports.ChunkStream.write (/Users/niftylettuce/Public/project/node_modules/pngjs/lib/chunkstream.js:61:8)
    at Inflate.<anonymous> (/Users/niftylettuce/Public/project/node_modules/pngjs/lib/parser-async.js:86:9)
    at emitOne (events.js:115:13)
    at Inflate.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Inflate.Readable.push (_stream_readable.js:197:10)
    at Inflate.Transform.push (_stream_transform.js:147:32)
    at Zlib.callback (zlib.js:473:14)
```

### PR DESCRIPTION
**Pull request by chrisdeely**

### CODE REVIEW

**Comment by sipayRT** [comment]
@chrisdeely can you squash commits and I will merge it

**Comment by scottrippey** [comment]
This would've saved me some headache ... ready to merge?

**Comment by chrisdeely** [comment]
@sipayRT an oldie but goodie - the commits are squashed as requested, should still be good to merge AFAIK

**Comment by sipayRT** [comment]
tnx for your PR. looks-same@7.2.0 was published

**Pull request merged**
